package edu.simulator.event;

public enum EventType {
    EMPLOYEE_RESIGNATION,
    CUSTOMER_FEATURE_REQUEST,
    PRODUCTION_BUG,
    DEPENDENCY_PROBLEM,
    REQUIREMENTS_MISUNDERSTANDING,
    FAILED_INTEGRATION,
    SECURITY_VULNERABILITY,
    KEY_EMPLOYEE_ILLNESS,
    TOOLING_FAILURE,
    COMPLIANCE_CHANGE,
    TECHNICAL_DEBT_ISSUE,
    PERFORMANCE_PROBLEM,
    STAKEHOLDER_CHANGE
}
